---
title: Further Education
---

<br style="float: none; clear: both" />

## ➔ Information technology

> ### Certificates


#### **2015** 	

* `Certificate in Geomatics and Regional Planning.` University of Guadalajara. The Mexican Commission for the Knowledge and Use of Biodiversity, CONABIO.

#### **2012** 	

* `Certificate in Linux Administration.` ITESO University 

#### **2007** 	

* `Certificate in Design and Production of Multimedia & Interactive Systems.` ITESO University 

---

> ### Workshops

#### **2022** 	

* `Search & Retrieval of Statistic and Geographical Information:` an update on new features and tools. UNAM - INEGI, México. 

#### **2018** 	

*    `Open-source library services platform FOLIO.` EBSCO Information Services & University of Guadalajara.

#### **2017** 	

*    `The Digital Map of Mexico platform.` National System of Statistical and Geographical Information, INEGI. México. 

#### **2016** 	

*    `Drupal Camp.` University of Guadalajara.

#### **2014** 	

*    `Open Access Journals.` University of Guadalajara. Guadalajara, México.

#### **2013** 	

*    `Weaving Academic E-learning Networks.` ITESO University (International Workshop).

#### **2012** 	

*    `Drupal Summit Latino.` University of Guadalajara.
*    `Intellectual Property workshop.` ITESO University.

<br style="float: none; clear: both" />

## ➔ Social Sciences

> ### Certificates

#### **2024** 	

* `Transparency, Privacy and Security in Digital Environments.` Institute of Transparency, Public Information and Protection of Personal Data of the State of Jalisco, ITEI.

#### **2010** 	

* `Social controllership: Citizen's right to Accountability.` ITESO University.

---

> ### Seminars & Workshops

#### **2024** 	

* `Webinar on Social Networks & Public Sector.` Institute of Transparency, Public Information and Protection of Personal Data of the State of Jalisco (ITEI); Chihuahua Institute for Transparency and Access to Public Information (ICHITAIP). 

#### **2022** 	

* `Seminar on Democracy, Governance & Civil Society.` El Colegio de Jalisco. Guadalajara, México. 

#### **2018** 	

* `XXII International Seminar on Communication & Society.` "Fake News, Post-Truth and Journalism Studies". University of Guadalajara. Guadalajara, México.
* `Social Research Projects: Strategies & Formulations.` ITESO - IBERO Universities.

#### **2017** 	

* `XXI International Seminar on Communication & Society.` "Youth and Digital Social Networks. Beliefs, results & perspectives in their research". University of Guadalajara. Guadalajara, México.

#### **2016** 	

* ` XX International Seminar on Communication & Society.` "Between knowing & recognizing oneself. Contemporary cultures in a world of migrations". University of Guadalajara. Guadalajara, México.
* `Society as Passion: Contributions to Systems Theory.` ITESO - IBERO Universities.

#### **2015** 	

* `Measurement of Public Policy results.` El Colegio de Jalisco. Guadalajara, México.
* `Innovation & Entrepreneurship Ecosystem.` ITESO University.

#### **2014** 	

* `Economic, Political & Environmental context analysis.` ITESO University.
* `Water, Governance & Political Ecology.` ITESO University.
* `Complex Thinking Paradigms.` ITESO University.
* `International Seminar on Communication & Society.` "Communication at the Center: Theory, Opinion & the Academic Field". ITESO University.

#### **2013** 	

* `General overview of Ethics.` ITESO & Deusto Universities.
* `Conflict resolution in México.` ITESO University.
* `The Convergence between Cultural Policies & Communication Policies in the Digital era.` ITESO University.

#### **2012** 	

* `Cultural Studies & Citizenship Culture.` ITESO University.
* `Citizenship, Human Rights & Peace.` ITESO University.
* `Citizenship, Neighborhood & Fraternity.` ITESO University.

#### **2011** 	

* `Ethics in Education for Social Coexistence.` ITESO University.
* `Seminar of Knowledge & Culture.` ITESO University.

